name: kronos_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.26.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0
  flutter_riverpod: ^2.6.1
  flutter_launcher_icons: ^0.14.4
  dio: ^5.9.2
  flutter_dotenv: ^6.0.0
  flutter_secure_storage: ^10.0.0
  flutter_web_auth_2: ^5.0.1
  flutter_screenutil: ^5.9.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.26.1
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/kronos_logo.jpg"
